version: '3.8'

services:
  build:
    container_name: questions-box-front
    build:
      context: .
      args:
        - deploy=build
    restart: always
    environment:
      TZ: "Asia/Tashkent"
    ports:
      - "8085:80"
    volumes:
      - ../data:/data
      - ../logs:/logs
